# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC
import requests
from hashlib import md5
from PIL import Image

username = '20171120143'
password = 'WAwa131452'
picpath = 'D:\\code'


class Chaojiying_Client(object):

    def __init__(self, username, password, soft_id):
        self.username = username
        self.password = password.encode('utf8')
        self.password = md5(self.password).hexdigest()
        self.soft_id = soft_id
        self.base_params = {
            'user': self.username,
            'pass2': self.password,
            'softid': self.soft_id,
        }
        self.headers = {
            'Connection': 'Keep-Alive',
            'User-Agent': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)',
        }

    def PostPic(self, im, codetype):
        """
        im: 图片字节
        codetype: 题目类型 参考 http://www.chaojiying.com/price.html
        """
        params = {
            'codetype': codetype,
        }
        params.update(self.base_params)
        files = {'userfile': ('ccc.jpg', im)}
        r = requests.post('http://upload.chaojiying.net/Upload/Processing.php', data=params, files=files,
                          headers=self.headers)
        return r.json()

    def ReportError(self, im_id):
        """
        im_id:报错题目的图片ID
        """
        params = {
            'id': im_id,
        }
        params.update(self.base_params)
        r = requests.post('http://upload.chaojiying.net/Upload/ReportError.php', data=params, headers=self.headers)
        return r.json()


class TestYnutest():
    def __init__(self, path, username, password):
        caps = {
            'browserName': 'chrome',
            'loggingPrefs': {
                'browser': 'ALL',
                'driver': 'ALL',
                'performance': 'ALL',
            },
            'goog:chromeOptions': {
                'perfLoggingPrefs': {
                    'enableNetwork': True,
                },
                'w3c': False,
            },
        }
        self.username = username
        self.password = password

        self.driver = webdriver.Chrome(desired_capabilities=caps, executable_path=path)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_ynutest(self):
        self.driver.maximize_window()
        self.driver.get(
            "https://ids.ynu.edu.cn/authserver/login?service=http%3A%2F%2Fehall.ynu.edu.cn%2Flogin%3Fservice%3Dhttp%3A%2F%2Fehall.ynu.edu.cn%2Fnew%2Findex.html")
        #     time.sleep(1)
        self.driver.save_screenshot(picpath + '1.png')
        self.driver.find_element_by_id('username').send_keys(self.username)
        self.driver.find_element_by_id('password').send_keys(self.password)
        # captchaimg = self.driver.find_element_by_id('captchaImg')
        # left = captchaimg.location['x']
        # top = captchaimg.location['y']
        # elementWidth = captchaimg.location['x'] + captchaimg.size['width']
        # elementHeight = captchaimg.location['y'] + captchaimg.size['height']
        # picture = Image.open(picpath + '1.png')
        # picture = picture.crop((left, top, elementWidth, elementHeight))
        # picture.save(picpath + '2.png')
        # chaojiying = Chaojiying_Client('sqasqasqa', 'lrtsqa1314', '905739')
        # im = open(picpath + '2.png', 'rb').read()  # 本地图片文件路径 来替换 a.jpg 有时WIN系统须要//
        # result = chaojiying.PostPic(im, 1902)['pic_str']
        # print(result)
        # self.driver.find_element_by_xpath('//*[@id="captchaResponse"]').send_keys(result)
        time.sleep(6)
        self.driver.find_element_by_tag_name('button').click()
        locator = (By.XPATH,
                   '//*[@id="widget-hot-01"]/div[1]/widget-app-item[1]/div/div/div[2]/div[1]')
        WebDriverWait(self.driver, 20, 0.5).until(EC.presence_of_element_located(locator))
        self.driver.find_element_by_xpath(
            '//*[@id="widget-hot-01"]/div[1]/widget-app-item[1]/div/div/div[2]/div[1]').click()
        windows = self.driver.window_handles
        self.driver.switch_to.window(windows[-1])
        self.driver.find_element_by_tag_name('a').click()
        locator = (By.TAG_NAME,
                   'tr')
        WebDriverWait(self.driver, 20, 0.5).until(EC.presence_of_element_located(locator))
        self.driver.find_elements_by_class_name('jqx-tabs-titleWrapper')[1].find_element_by_tag_name('div').click()
        time.sleep(5)
        self.driver.find_element_by_xpath(
            '/html/body/main/article/section/div[3]/div/div[2]/div[2]/section/div/div[2]/div/div[10]/div/div/div[2]/div/div/div').click()
        time.sleep(4)
        self.driver.find_element_by_xpath('/html/body/div[9]/div/div/div/div[2]/div/div[3]/span').click()
        time.sleep(4)

        request_log = self.driver.get_log('performance')
        #
        result = {}
        for i in range(len(request_log)):
            message = json.loads(request_log[i]['message'])
            message = message['message']['params']
            # .get() 方式获取是了避免字段不存在时报错
            request = message.get('request')
            if request is None:
                continue

            url = request.get('url')
            # print('**********',url)
            if url == "http://ehall.ynu.edu.cn/jwapp/sys/cjcx/modules/cjcx/xscjcx.do":
                content = self.driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': message['requestId']})
        coursescores = json.loads(content['body'])['datas']['xscjcx']['rows']
        result['coursescores'] = coursescores
        # print(coursescores)
        self.driver.find_element_by_xpath('/html/body/header/header[1]/div/div/div[4]/div[4]/a[1]/div').click()
        time.sleep(10)
        request_log = self.driver.get_log('performance')
        print(request_log)

        for i in range(len(request_log)):
            message = json.loads(request_log[i]['message'])
            message = message['message']['params']
            # .get() 方式获取是了避免字段不存在时报错
            request = message.get('request')
            if request is None:
                continue

            url = request.get('url')
            print(url)
            # if url == "http://ehall.ynu.edu.cn/jwapp/sys/cjcx/modules/cjcx/xscjcx.do":
            #     content = self.driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': message['requestId']})
            #     print("成绩：", content)
            #     coursescores = json.loads(content['body'])['datas']['xscjcx']['rows']
            #     result['coursescores'] = coursescores
            if url == "http://ehall.ynu.edu.cn/jwapp/sys/cjcx/modules/cjfx/xscjtjcx.do":  # GPA
                # 得到requestId
                print(message['requestId'])
                # 通过requestId获取接口内容
                content = self.driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': message['requestId']})
                print("GPA：", content)
                gpa_content = json.loads(content['body'])['datas']['xscjtjcx']['rows']  # GPA
                result['gpa_content'] = gpa_content

            if url == 'http://ehall.ynu.edu.cn/jwapp/sys/cjcx/modules/cjfx/xscjfbcx.do':
                print(message['requestId'])
                num_content = self.driver.execute_cdp_cmd('Network.getResponseBody',
                                                          {'requestId': message['requestId']})
                print("分布：", num_content)
                num_content = json.loads(num_content['body'])['datas']['xscjfbcx']['rows']

                result['num_content'] = num_content
        print(result)
        return result


if __name__ == '__main__':
    test = TestYnutest('D:\\只狼\\chromedriver.exe', '20171120028', 'lrtsqa1314A')
    test.test_ynutest()
