# Generated by Django 3.0.6 on 2020-06-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
