# Generated by Django 3.0.6 on 2020-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20171218_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonsName', models.CharField(max_length=100)),
                ('lessonsAddress', models.CharField(blank=True, max_length=100)),
                ('lessonsTeacher', models.CharField(max_length=10)),
                ('XQ1', models.CharField(max_length=10)),
                ('XQ2', models.CharField(max_length=10)),
                ('XQ3', models.CharField(max_length=10)),
                ('XQ4', models.CharField(max_length=10)),
                ('XQ5', models.CharField(max_length=10)),
            ],
        ),
    ]
