# Generated by Django 3.0.6 on 2020-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20200531_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_table',
            name='XQ1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course_table',
            name='XQ2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course_table',
            name='XQ3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course_table',
            name='XQ4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course_table',
            name='XQ5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
