# Generated by Django 3.0.6 on 2020-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200531_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_table',
            name='lessonsTeacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
