# Generated by Django 3.0.6 on 2020-05-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20200531_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessonAddress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='college_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.SmallIntegerField(default=64),
        ),
    ]
