# Generated by Django 3.0.6 on 2020-05-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200531_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lessonAddress',
            new_name='lessonsAddress',
        ),
    ]
