# Generated by Django 3.0.6 on 2020-06-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20200531_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestudentgrade',
            old_name='student',
            new_name='user',
        ),
    ]
