# Generated by Django 3.0.6 on 2020-06-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20200601_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='XQ1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='XQ2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='XQ3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='XQ4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='XQ5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
